// Generates src/engine/data/removal169.ts: sensitivity of preflop equity to the composition of
// dead cards (cards held by players who folded).
//
// SENS[h][j] = change in equity of class h vs class j when one dead card is a broadway card
// (T-A) instead of a lower card. Estimated with paired sampling: with dead card b (broadway) or l
// (low), the boards differ only when they contain the other card, so
//   eq(dead b) - eq(dead l) = 5/47 · E[win(board4 ∪ {l}) - win(board4 ∪ {b})].
// Usage: npm run gen:removal -- [samplesPerPair]

import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { availableParallelism } from 'node:os';
import { writeFileSync } from 'node:fs';
import { classCombos, NUM_CLASSES } from '../src/engine/cards';
import { evaluate7 } from '../src/engine/evaluator';

type Job = { hs: number[]; samples: number; seed: number };
const BROADWAY_MIN_RANK = 8; // rank index 8 = T (0 = 2)

function rng(seed: number) {
  let s = seed >>> 0 || 1;
  return () => {
    s ^= s << 13; s >>>= 0;
    s ^= s >> 17;
    s ^= s << 5; s >>>= 0;
    return s / 4294967296;
  };
}

function runJob({ hs, samples, seed }: Job): Array<[number, Float64Array]> {
  const rand = rng(seed);
  const combos = Array.from({ length: NUM_CLASSES }, (_, i) => classCombos(i));
  const a = new Int32Array(7);
  const b = new Int32Array(7);
  const hi: number[] = [];
  const lo: number[] = [];
  const rest: number[] = [];
  const out: Array<[number, Float64Array]> = [];
  for (const h of hs) {
    const row = new Float64Array(NUM_CLASSES);
    for (let j = h; j < NUM_CLASSES; j++) {
      const pairs: Array<[number, number, number, number]> = [];
      for (const [c1, c2] of combos[h])
        for (const [d1, d2] of combos[j])
          if (c1 !== d1 && c1 !== d2 && c2 !== d1 && c2 !== d2) pairs.push([c1, c2, d1, d2]);
      if (pairs.length === 0) continue;
      let sum = 0;
      for (let s = 0; s < samples; s++) {
        const [c1, c2, d1, d2] = pairs[(rand() * pairs.length) | 0];
        hi.length = 0; lo.length = 0;
        for (let c = 0; c < 52; c++) {
          if (c === c1 || c === c2 || c === d1 || c === d2) continue;
          ((c >> 2) >= BROADWAY_MIN_RANK ? hi : lo).push(c);
        }
        const bw = hi[(rand() * hi.length) | 0];
        const lw = lo[(rand() * lo.length) | 0];
        rest.length = 0;
        for (let c = 0; c < 52; c++) if (c !== c1 && c !== c2 && c !== d1 && c !== d2 && c !== bw && c !== lw) rest.push(c);
        for (let k = 0; k < 4; k++) {
          const idx = k + ((rand() * (rest.length - k)) | 0);
          const t = rest[k]; rest[k] = rest[idx]; rest[idx] = t;
          a[2 + k] = rest[k];
          b[2 + k] = rest[k];
        }
        a[0] = c1; a[1] = c2; b[0] = d1; b[1] = d2;
        // board with the low card (broadway card dead)
        a[6] = lw; b[6] = lw;
        const ea1 = evaluate7(a), eb1 = evaluate7(b);
        const w1 = ea1 > eb1 ? 1 : ea1 === eb1 ? 0.5 : 0;
        // board with the broadway card (low card dead)
        a[6] = bw; b[6] = bw;
        const ea2 = evaluate7(a), eb2 = evaluate7(b);
        const w2 = ea2 > eb2 ? 1 : ea2 === eb2 ? 0.5 : 0;
        sum += w1 - w2;
      }
      row[j] = (5 / 47) * (sum / samples);
    }
    out.push([h, row]);
  }
  return out;
}

if (!isMainThread) {
  parentPort!.postMessage(runJob(workerData as Job));
} else {
  const samples = Number(process.argv[2] ?? 60000);
  const threads = Math.max(1, availableParallelism() - 2);
  const buckets: number[][] = Array.from({ length: threads }, () => []);
  for (let h = 0; h < NUM_CLASSES; h++) buckets[h % threads].push(h);
  const t0 = Date.now();
  const results = await Promise.all(
    buckets.map(
      (hs, i) =>
        new Promise<Array<[number, Float64Array]>>((resolve, reject) => {
          const w = new Worker(new URL(import.meta.url), { workerData: { hs, samples, seed: 777 + i * 7919 } });
          w.on('message', resolve);
          w.on('error', reject);
        }),
    ),
  );
  const sens = new Float64Array(NUM_CLASSES * NUM_CLASSES);
  for (const part of results)
    for (const [h, row] of part)
      for (let j = h; j < NUM_CLASSES; j++) {
        sens[h * NUM_CLASSES + j] = row[j];
        sens[j * NUM_CLASSES + h] = -row[j];
      }
  for (let h = 0; h < NUM_CLASSES; h++) sens[h * NUM_CLASSES + h] = 0;
  const SCALE = 8192 * 16; // 1 unit = 1/131072 equity per card
  const q = Int16Array.from(sens, (v) => Math.max(-32768, Math.min(32767, Math.round(v * SCALE))));
  let maxAbs = 0;
  for (const v of sens) maxAbs = Math.max(maxAbs, Math.abs(v));
  writeFileSync(
    new URL('../src/engine/data/removal169.ts', import.meta.url),
    `// Generated by scripts/gen-removal.ts (${samples} paired samples per class pair). Do not edit.\n` +
      `// Int16 little-endian, value/${SCALE} = equity change of row vs column per dead broadway card.\n` +
      `export const REMOVAL_SCALE = ${SCALE};\nexport const REMOVAL169_B64 =\n  '${Buffer.from(new Uint8Array(q.buffer)).toString('base64')}';\n`,
  );
  console.log(`done in ${((Date.now() - t0) / 1000).toFixed(1)}s, max |sens| = ${(maxAbs * 100).toFixed(2)}% per card`);
}
