// Generates src/engine/data/equity169.ts: preflop all-in equity of class h vs class j
// (win + tie/2), averaged over compatible combo pairs, via Monte Carlo.
// Usage: npm run gen:equity -- [samplesPerPair]

import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { availableParallelism } from 'node:os';
import { writeFileSync } from 'node:fs';
import { classCombos, NUM_CLASSES } from '../src/engine/cards.ts';
import { evaluate7 } from '../src/engine/evaluator.ts';

type Job = { hs: number[]; samples: number; seed: number };

function rng(seed: number) {
  let s = seed >>> 0 || 1;
  return () => {
    s ^= s << 13; s >>>= 0;
    s ^= s >> 17;
    s ^= s << 5; s >>>= 0;
    return s / 4294967296;
  };
}

function runJob({ hs, samples, seed }: Job): Array<[number, Float64Array]> {
  const rand = rng(seed);
  const combos = Array.from({ length: NUM_CLASSES }, (_, i) => classCombos(i));
  const a = new Int32Array(7);
  const b = new Int32Array(7);
  const deck = new Int32Array(52);
  const out: Array<[number, Float64Array]> = [];
  for (const h of hs) {
    const row = new Float64Array(NUM_CLASSES);
    for (let j = h; j < NUM_CLASSES; j++) {
      const pairs: Array<[number, number, number, number]> = [];
      for (const [c1, c2] of combos[h])
        for (const [d1, d2] of combos[j])
          if (c1 !== d1 && c1 !== d2 && c2 !== d1 && c2 !== d2) pairs.push([c1, c2, d1, d2]);
      if (pairs.length === 0) { row[j] = 0.5; continue; }
      let score = 0;
      for (let s = 0; s < samples; s++) {
        const [c1, c2, d1, d2] = pairs[(rand() * pairs.length) | 0];
        let n = 0;
        for (let c = 0; c < 52; c++) if (c !== c1 && c !== c2 && c !== d1 && c !== d2) deck[n++] = c;
        for (let k = 0; k < 5; k++) {
          const idx = k + ((rand() * (n - k)) | 0);
          const t = deck[k]; deck[k] = deck[idx]; deck[idx] = t;
          a[2 + k] = deck[k];
          b[2 + k] = deck[k];
        }
        a[0] = c1; a[1] = c2; b[0] = d1; b[1] = d2;
        const ea = evaluate7(a);
        const eb = evaluate7(b);
        score += ea > eb ? 1 : ea === eb ? 0.5 : 0;
      }
      row[j] = score / samples;
    }
    out.push([h, row]);
  }
  return out;
}

if (!isMainThread) {
  parentPort!.postMessage(runJob(workerData as Job));
} else {
  const samples = Number(process.argv[2] ?? 40000);
  const threads = Math.max(1, availableParallelism() - 2);
  const buckets: number[][] = Array.from({ length: threads }, () => []);
  // interleave rows so work per thread is balanced (row h has 169-h cells)
  for (let h = 0; h < NUM_CLASSES; h++) buckets[h % threads].push(h);
  const t0 = Date.now();
  console.log(`samples/pair=${samples} threads=${threads}`);
  const results = await Promise.all(
    buckets.map(
      (hs, i) =>
        new Promise<Array<[number, Float64Array]>>((resolve, reject) => {
          const w = new Worker(new URL(import.meta.url), { workerData: { hs, samples, seed: 12345 + i * 7919 } });
          w.on('message', resolve);
          w.on('error', reject);
        }),
    ),
  );
  const eq = new Float64Array(NUM_CLASSES * NUM_CLASSES);
  for (const part of results)
    for (const [h, row] of part)
      for (let j = h; j < NUM_CLASSES; j++) {
        eq[h * NUM_CLASSES + j] = row[j];
        eq[j * NUM_CLASSES + h] = 1 - row[j];
      }
  for (let h = 0; h < NUM_CLASSES; h++) eq[h * NUM_CLASSES + h] = 0.5;
  const q = new Uint16Array(NUM_CLASSES * NUM_CLASSES);
  for (let i = 0; i < q.length; i++) q[i] = Math.round(eq[i] * 65535);
  const b64 = Buffer.from(q.buffer).toString('base64');
  writeFileSync(
    new URL('../src/engine/data/equity169.ts', import.meta.url),
    `// Generated by scripts/gen-equity.ts (${samples} samples per class pair). Do not edit.\n` +
      `// Uint16 little-endian, value/65535 = equity of row class vs column class.\n` +
      `export const EQUITY169_B64 =\n  '${b64}';\n`,
  );
  console.log(`done in ${((Date.now() - t0) / 1000).toFixed(1)}s`);
}
